spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/side_project/sickdan/server/sickdan
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    open-in-view: false
  jwt:
    secret-key: kdPark
  servlet:
    multipart:


logging:
  level:
    org.hibernate.SQL: debug
filepath: