spring:
  datasource:
    url: jdbc:mariadb://dbinstance-1.cveiyepjwzwd.ap-northeast-2.rds.amazonaws.com:3306/sickdan
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
  redis:
    port: 6379
    host: 222.111.195.42

cloud:
  aws:
    s3:
      bucket: sickdan-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug
filepath:

